//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeminiAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeminiAssistant.Properties.EnglishResources", typeof(EnglishResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screenshot ready · {0} KB · {1}.
        /// </summary>
        internal static string Capture_ReadyLabel {
            get {
                return ResourceManager.GetString("Capture_ReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a capture.
        /// </summary>
        internal static string Capture_Source_Default {
            get {
                return ResourceManager.GetString("Capture_Source_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Bar.
        /// </summary>
        internal static string Capture_Source_GameBar {
            get {
                return ResourceManager.GetString("Capture_Source_GameBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a game window.
        /// </summary>
        internal static string Capture_Source_GameWindow {
            get {
                return ResourceManager.GetString("Capture_Source_GameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a selected window.
        /// </summary>
        internal static string Capture_Source_Window {
            get {
                return ResourceManager.GetString("Capture_Source_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detecting game....
        /// </summary>
        internal static string Chat_DetectingGame {
            get {
                return ResourceManager.GetString("Chat_DetectingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Achievements.
        /// </summary>
        internal static string Chat_FabAchievements {
            get {
                return ResourceManager.GetString("Chat_FabAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture.
        /// </summary>
        internal static string Chat_FabCapture {
            get {
                return ResourceManager.GetString("Chat_FabCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        internal static string Chat_FabStats {
            get {
                return ResourceManager.GetString("Chat_FabStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tips.
        /// </summary>
        internal static string Chat_FabTips {
            get {
                return ResourceManager.GetString("Chat_FabTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active game.
        /// </summary>
        internal static string Chat_GameActive {
            get {
                return ResourceManager.GetString("Chat_GameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello.
        /// </summary>
        internal static string Chat_GreetingHello {
            get {
                return ResourceManager.GetString("Chat_GreetingHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How can I .
        /// </summary>
        internal static string Chat_GreetingHelpPart1 {
            get {
                return ResourceManager.GetString("Chat_GreetingHelpPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a help you today?.
        /// </summary>
        internal static string Chat_GreetingHelpPart2 {
            get {
                return ResourceManager.GetString("Chat_GreetingHelpPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ask me anything.
        /// </summary>
        internal static string Chat_InputPlaceholder {
            get {
                return ResourceManager.GetString("Chat_InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a message....
        /// </summary>
        internal static string Chat_InputPlaceholderActive {
            get {
                return ResourceManager.GetString("Chat_InputPlaceholderActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear chat.
        /// </summary>
        internal static string Chat_MenuClear {
            get {
                return ResourceManager.GetString("Chat_MenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View log.
        /// </summary>
        internal static string Chat_MenuLog {
            get {
                return ResourceManager.GetString("Chat_MenuLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Chat_MenuSettings {
            get {
                return ResourceManager.GetString("Chat_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ME.
        /// </summary>
        internal static string Chat_ProfileInitials {
            get {
                return ResourceManager.GetString("Chat_ProfileInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture the game screen.
        /// </summary>
        internal static string Chat_SuggestionCaptureSub {
            get {
                return ResourceManager.GetString("Chat_SuggestionCaptureSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyze screenshot.
        /// </summary>
        internal static string Chat_SuggestionCaptureTitle {
            get {
                return ResourceManager.GetString("Chat_SuggestionCaptureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Based on your active session.
        /// </summary>
        internal static string Chat_SuggestionGamesSub {
            get {
                return ResourceManager.GetString("Chat_SuggestionGamesSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game recommendations.
        /// </summary>
        internal static string Chat_SuggestionGamesTitle {
            get {
                return ResourceManager.GetString("Chat_SuggestionGamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query real achievements via Steam Web API.
        /// </summary>
        internal static string Chat_SuggestionSteamSub {
            get {
                return ResourceManager.GetString("Chat_SuggestionSteamSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Steam achievements.
        /// </summary>
        internal static string Chat_SuggestionSteamTitle {
            get {
                return ResourceManager.GetString("Chat_SuggestionSteamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture screen.
        /// </summary>
        internal static string Chat_TooltipCapture {
            get {
                return ResourceManager.GetString("Chat_TooltipCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Chat_TooltipHome {
            get {
                return ResourceManager.GetString("Chat_TooltipHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record voice.
        /// </summary>
        internal static string Chat_TooltipMic {
            get {
                return ResourceManager.GetString("Chat_TooltipMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More options.
        /// </summary>
        internal static string Chat_TooltipMore {
            get {
                return ResourceManager.GetString("Chat_TooltipMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove screenshot.
        /// </summary>
        internal static string Chat_TooltipRemoveCapture {
            get {
                return ResourceManager.GetString("Chat_TooltipRemoveCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        internal static string Chat_TooltipSend {
            get {
                return ResourceManager.GetString("Chat_TooltipSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YOU.
        /// </summary>
        internal static string Chat_UserInitials {
            get {
                return ResourceManager.GetString("Chat_UserInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a app.
        /// </summary>
        internal static string Ctx_AppLabel {
            get {
                return ResourceManager.GetString("Ctx_AppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , fullscreen.
        /// </summary>
        internal static string Ctx_FullscreenSuffix {
            get {
                return ResourceManager.GetString("Ctx_FullscreenSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are a gaming assistant in Xbox Game Bar. The player is in: {0}. Is game: {1}. Fullscreen: {2}. AumId: {3}. TitleId: {4}. Give tips, strategies and answers relevant to that title. If the message includes Steam Web API data, combine it with the active game context. Respond in English..
        /// </summary>
        internal static string Ctx_GameInstruction {
            get {
                return ResourceManager.GetString("Ctx_GameInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a game.
        /// </summary>
        internal static string Ctx_GameLabel {
            get {
                return ResourceManager.GetString("Ctx_GameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game tracking disabled in Game Bar.
        /// </summary>
        internal static string Ctx_TrackingDisabled {
            get {
                return ResourceManager.GetString("Ctx_TrackingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are a gaming assistant in Xbox Game Bar. Active game tracking is disabled; give general advice if you do not know the title. Respond in English..
        /// </summary>
        internal static string Ctx_UnknownInstruction {
            get {
                return ResourceManager.GetString("Ctx_UnknownInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screenshot: {0}.
        /// </summary>
        internal static string Error_CapturePrefix {
            get {
                return ResourceManager.GetString("Error_CapturePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microphone permission denied. Settings &gt; Privacy &gt; Microphone &gt; Gemini Assistant..
        /// </summary>
        internal static string Error_MicDenied {
            get {
                return ResourceManager.GetString("Error_MicDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microphone: {0}.
        /// </summary>
        internal static string Error_MicPrefix {
            get {
                return ResourceManager.GetString("Error_MicPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API key missing. Open the widget Settings..
        /// </summary>
        internal static string Error_MissingApiKey {
            get {
                return ResourceManager.GetString("Error_MissingApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For Steam or achievement questions, set Steam Web API Key and SteamID64 in Settings..
        /// </summary>
        internal static string Error_MissingSteam {
            get {
                return ResourceManager.GetString("Error_MissingSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not initialize speech recognition. Install the speech language pack in Windows..
        /// </summary>
        internal static string Error_SpeechInit {
            get {
                return ResourceManager.GetString("Error_SpeechInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No response from Steam. Check your API key and SteamID64 in Settings (they must match what works in the browser)..
        /// </summary>
        internal static string Error_SteamNoResponse {
            get {
                return ResourceManager.GetString("Error_SteamNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam: {0}.
        /// </summary>
        internal static string Error_SteamPrefix {
            get {
                return ResourceManager.GetString("Error_SteamPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error (the widget may have closed during the request)..
        /// </summary>
        internal static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voice recording cancelled..
        /// </summary>
        internal static string Error_VoiceCancelled {
            get {
                return ResourceManager.GetString("Error_VoiceCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write what you want to know about the screenshot and press Send..
        /// </summary>
        internal static string Error_WriteCapturePrompt {
            get {
                return ResourceManager.GetString("Error_WriteCapturePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App in foreground.
        /// </summary>
        internal static string Game_AppForeground {
            get {
                return ResourceManager.GetString("Game_AppForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable game tracking in Game Bar.
        /// </summary>
        internal static string Game_EnableTracking {
            get {
                return ResourceManager.GetString("Game_EnableTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No game detected.
        /// </summary>
        internal static string Game_NoGameDetected {
            get {
                return ResourceManager.GetString("Game_NoGameDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Playing now.
        /// </summary>
        internal static string Game_PlayingNow {
            get {
                return ResourceManager.GetString("Game_PlayingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracking disabled.
        /// </summary>
        internal static string Game_TrackingOff {
            get {
                return ResourceManager.GetString("Game_TrackingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable tracking in Game Bar.
        /// </summary>
        internal static string Game_TrackingOffHint {
            get {
                return ResourceManager.GetString("Game_TrackingOffHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        internal static string Game_Unknown {
            get {
                return ResourceManager.GetString("Game_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for game.
        /// </summary>
        internal static string Game_WaitingGame {
            get {
                return ResourceManager.GetString("Game_WaitingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gemini API ({0}): {1}.
        /// </summary>
        internal static string Gemini_ApiError {
            get {
                return ResourceManager.GetString("Gemini_ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gemini API error ({0}).
        /// </summary>
        internal static string Gemini_ApiErrorGeneric {
            get {
                return ResourceManager.GetString("Gemini_ApiErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure your API key in widget Settings..
        /// </summary>
        internal static string Gemini_ConfigApiKey {
            get {
                return ResourceManager.GetString("Gemini_ConfigApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The recorded audio is empty..
        /// </summary>
        internal static string Gemini_EmptyAudio {
            get {
                return ResourceManager.GetString("Gemini_EmptyAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gemini returned no text in the response..
        /// </summary>
        internal static string Gemini_NoTextResponse {
            get {
                return ResourceManager.GetString("Gemini_NoTextResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Respond clearly and directly; avoid unnecessary filler..
        /// </summary>
        internal static string Gemini_RespondClearly {
            get {
                return ResourceManager.GetString("Gemini_RespondClearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Response blocked: {0}.
        /// </summary>
        internal static string Gemini_ResponseBlocked {
            get {
                return ResourceManager.GetString("Gemini_ResponseBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Response truncated due to length limit. Ask for more detail if needed.].
        /// </summary>
        internal static string Gemini_ResponseTruncated {
            get {
                return ResourceManager.GetString("Gemini_ResponseTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  The user has Steam Web API Key and SteamID64 saved in widget Settings; the system queries Steam automatically on achievement questions. NEVER ask the user to configure, paste or share the API key or SteamID64. When the message includes a &apos;Real Steam Web API data&apos; block, use that data as verified source. If the block is for a different game than earlier turns, use only the new block. Do not say the profile is private if the data indicates another issue. Do not say you lack Steam access if that data is prese [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Gemini_SteamConfigured {
            get {
                return ResourceManager.GetString("Gemini_SteamConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Do not ask for API key or SteamID64; they are already configured. Do not invent data or claim a private profile if the data is already above..
        /// </summary>
        internal static string Gemini_SteamContextSuffix {
            get {
                return ResourceManager.GetString("Gemini_SteamContextSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listen to the player&apos;s audio. Transcribe it and respond as a gaming assistant. If there is no audible speech, say so clearly..
        /// </summary>
        internal static string Gemini_VoiceInstruction {
            get {
                return ResourceManager.GetString("Gemini_VoiceInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyzing voice.
        /// </summary>
        internal static string Msg_AnalyzingVoice {
            get {
                return ResourceManager.GetString("Msg_AnalyzingVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gemini.
        /// </summary>
        internal static string Msg_Gemini {
            get {
                return ResourceManager.GetString("Msg_Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.
        /// </summary>
        internal static string Msg_System {
            get {
                return ResourceManager.GetString("Msg_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You.
        /// </summary>
        internal static string Msg_User {
            get {
                return ResourceManager.GetString("Msg_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You (voice).
        /// </summary>
        internal static string Msg_UserVoice {
            get {
                return ResourceManager.GetString("Msg_UserVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Give me tips for this game.
        /// </summary>
        internal static string Prompt_FabTips {
            get {
                return ResourceManager.GetString("Prompt_FabTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game recommendations for my profile.
        /// </summary>
        internal static string Prompt_GameRecommendations {
            get {
                return ResourceManager.GetString("Prompt_GameRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyze Steam achievements: {0} ({1}/{2}).
        /// </summary>
        internal static string Prompt_SteamAchievementsDisplay {
            get {
                return ResourceManager.GetString("Prompt_SteamAchievementsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyze my Steam achievements for this game. Tell me which ones I&apos;m missing, which are easiest to get now, and concrete tips to unlock them..
        /// </summary>
        internal static string Prompt_SteamAchievementsGemini {
            get {
                return ResourceManager.GetString("Prompt_SteamAchievementsGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyze Steam profile: {0} ({1} games).
        /// </summary>
        internal static string Prompt_SteamProfileDisplay {
            get {
                return ResourceManager.GetString("Prompt_SteamProfileDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyze my Steam profile: library summary, most played games, and useful suggestions based on my playtime..
        /// </summary>
        internal static string Prompt_SteamProfileGemini {
            get {
                return ResourceManager.GetString("Prompt_SteamProfileGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get one at aistudio.google.com/apikey.
        /// </summary>
        internal static string Settings_ApiKeyHint {
            get {
                return ResourceManager.GetString("Settings_ApiKeyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Google AI Studio API key.
        /// </summary>
        internal static string Settings_ApiKeyLabel {
            get {
                return ResourceManager.GetString("Settings_ApiKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste your API key.
        /// </summary>
        internal static string Settings_ApiKeyPlaceholder {
            get {
                return ResourceManager.GetString("Settings_ApiKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When you tap Capture, Windows may ask for permission (choose Allow). If it fails: Settings &gt; Privacy &amp; security &gt; Screen capture &gt; Gemini Assistant. Click the game before capturing if Game Bar is open..
        /// </summary>
        internal static string Settings_CaptureHint {
            get {
                return ResourceManager.GetString("Settings_CaptureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screen capture.
        /// </summary>
        internal static string Settings_CaptureTitle {
            get {
                return ResourceManager.GetString("Settings_CaptureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatic (system).
        /// </summary>
        internal static string Settings_Language_Auto {
            get {
                return ResourceManager.GetString("Settings_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string Settings_Language_Spanish {
            get {
                return ResourceManager.GetString("Settings_Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved..
        /// </summary>
        internal static string Settings_Saved {
            get {
                return ResourceManager.GetString("Settings_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Language updated..
        /// </summary>
        internal static string Settings_SavedLanguageNote {
            get {
                return ResourceManager.GetString("Settings_SavedLanguageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key at steamcommunity.com/dev (32 characters). SteamID64 at steamid.io. Set profile and Game details to Public (Steam &gt; Edit profile &gt; Privacy). If you see 403: do not use IP whitelist with 127.0.0.1..
        /// </summary>
        internal static string Settings_SteamHint {
            get {
                return ResourceManager.GetString("Settings_SteamHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SteamID64.
        /// </summary>
        internal static string Settings_SteamIdLabel {
            get {
                return ResourceManager.GetString("Settings_SteamIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam Web API Key.
        /// </summary>
        internal static string Settings_SteamKeyLabel {
            get {
                return ResourceManager.GetString("Settings_SteamKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings — Gemini Assistant.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture: enable screen capture permission in Windows Settings..
        /// </summary>
        internal static string Status_CapturePermission {
            get {
                return ResourceManager.GetString("Status_CapturePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screenshot restored. Type your message and press Send..
        /// </summary>
        internal static string Status_CaptureRestored {
            get {
                return ResourceManager.GetString("Status_CaptureRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not restore screenshot: {0}.
        /// </summary>
        internal static string Status_CaptureRestoreFailed {
            get {
                return ResourceManager.GetString("Status_CaptureRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture takes a game screenshot automatically. Enter sends..
        /// </summary>
        internal static string Status_CaptureTip {
            get {
                return ResourceManager.GetString("Status_CaptureTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturing game screen....
        /// </summary>
        internal static string Status_Capturing {
            get {
                return ResourceManager.GetString("Status_Capturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagnostic: {0}.
        /// </summary>
        internal static string Status_Diagnostic {
            get {
                return ResourceManager.GetString("Status_Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log: {0}.
        /// </summary>
        internal static string Status_LogPrefix {
            get {
                return ResourceManager.GetString("Status_LogPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set your API key in Settings (gear icon in Game Bar)..
        /// </summary>
        internal static string Status_NoApiKey {
            get {
                return ResourceManager.GetString("Status_NoApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entries in widget-diagnostic.log.
        /// </summary>
        internal static string Status_NoLog {
            get {
                return ResourceManager.GetString("Status_NoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing audio....
        /// </summary>
        internal static string Status_ProcessingAudio {
            get {
                return ResourceManager.GetString("Status_ProcessingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Querying Steam....
        /// </summary>
        internal static string Status_QueryingSteam {
            get {
                return ResourceManager.GetString("Status_QueryingSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Querying Steam achievements....
        /// </summary>
        internal static string Status_QueryingSteamAchievements {
            get {
                return ResourceManager.GetString("Status_QueryingSteamAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Querying Steam profile....
        /// </summary>
        internal static string Status_QueryingSteamProfile {
            get {
                return ResourceManager.GetString("Status_QueryingSteamProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recording... Tap the microphone again to stop and send..
        /// </summary>
        internal static string Status_Recording {
            get {
                return ResourceManager.GetString("Status_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum recording time reached, sending....
        /// </summary>
        internal static string Status_RecordingMax {
            get {
                return ResourceManager.GetString("Status_RecordingMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Screenshot ready. Type your message and press Send or Enter..
        /// </summary>
        internal static string Status_ScreenshotReady {
            get {
                return ResourceManager.GetString("Status_ScreenshotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sending to Gemini....
        /// </summary>
        internal static string Status_SendingGemini {
            get {
                return ResourceManager.GetString("Status_SendingGemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam OK — sending to Gemini....
        /// </summary>
        internal static string Status_SteamOk {
            get {
                return ResourceManager.GetString("Status_SteamOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gemini is transcribing your voice....
        /// </summary>
        internal static string Status_Transcribing {
            get {
                return ResourceManager.GetString("Status_Transcribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait for the previous send to finish..
        /// </summary>
        internal static string Status_WaitSend {
            get {
                return ResourceManager.GetString("Status_WaitSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam allows viewing your library but blocks achievements (the API responds &quot;Profile is not public&quot;). This is not an API key failure..
        /// </summary>
        internal static string Steam_AchievementsBlocked {
            get {
                return ResourceManager.GetString("Steam_AchievementsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Also check:.
        /// </summary>
        internal static string Steam_Checklist_AlsoCheck {
            get {
                return ResourceManager.GetString("Steam_Checklist_AlsoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a    (game: {0}).
        /// </summary>
        internal static string Steam_Checklist_GameLine {
            get {
                return ResourceManager.GetString("Steam_Checklist_GameLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam API diagnostic:.
        /// </summary>
        internal static string Steam_Checklist_Header {
            get {
                return ResourceManager.GetString("Steam_Checklist_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Steam &gt; Library &gt; right-click the game &gt; Manage &gt; must NOT be &quot;Mark as private&quot;..
        /// </summary>
        internal static string Steam_Checklist_Item1 {
            get {
                return ResourceManager.GetString("Steam_Checklist_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. Privacy: set Game details to Friends only, save, switch back to Public and restart the Steam client..
        /// </summary>
        internal static string Steam_Checklist_Item2 {
            get {
                return ResourceManager.GetString("Steam_Checklist_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. Open in a private window (not logged in):.
        /// </summary>
        internal static string Steam_Checklist_Item3 {
            get {
                return ResourceManager.GetString("Steam_Checklist_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4. Verify SteamID64 in Settings with GetPlayerSummaries in the browser..
        /// </summary>
        internal static string Steam_Checklist_Item4 {
            get {
                return ResourceManager.GetString("Steam_Checklist_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5. Limited Steam accounts (&lt;5 USD) may block public data..
        /// </summary>
        internal static string Steam_Checklist_Item5 {
            get {
                return ResourceManager.GetString("Steam_Checklist_Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6. Privacy changes may take several minutes to propagate..
        /// </summary>
        internal static string Steam_Checklist_Item6 {
            get {
                return ResourceManager.GetString("Steam_Checklist_Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   The API does NOT see your profile as public (must be 3). Adjust My profile in Privacy, not just Game details..
        /// </summary>
        internal static string Steam_Checklist_NotPublicNote {
            get {
                return ResourceManager.GetString("Steam_Checklist_NotPublicNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Profile queried: {0}.
        /// </summary>
        internal static string Steam_Checklist_ProfileQueried {
            get {
                return ResourceManager.GetString("Steam_Checklist_ProfileQueried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - communityvisibilitystate: {0} ({1}).
        /// </summary>
        internal static string Steam_Checklist_VisibilityLine {
            get {
                return ResourceManager.GetString("Steam_Checklist_VisibilityLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Detail: {0}.
        /// </summary>
        internal static string Steam_DetailSuffix {
            get {
                return ResourceManager.GetString("Steam_DetailSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam returned an empty response (HTTP {0})..
        /// </summary>
        internal static string Steam_EmptyResponse {
            get {
                return ResourceManager.GetString("Steam_EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your profile is {0} to the API, but the library or achievements are not accessible. Steam &gt; your profile &gt; Edit profile &gt; Privacy &gt; set Public: Game details (and Game achievements if shown). The profile may look fine in the browser when logged in, but the API queries as an external visitor..
        /// </summary>
        internal static string Steam_GameDetailsHidden {
            get {
                return ResourceManager.GetString("Steam_GameDetailsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find &quot;{0}&quot; in your Steam library ({1} games). Check the exact game name on Steam..
        /// </summary>
        internal static string Steam_GameNotFound {
            get {
                return ResourceManager.GetString("Steam_GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam rejected the API Key (HTTP 401). Copy the key from steamcommunity.com/dev with no spaces..
        /// </summary>
        internal static string Steam_Http401 {
            get {
                return ResourceManager.GetString("Steam_Http401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam rejected access (HTTP 403). Check the key in widget Settings (it must match what works in the browser). If the key has an IP whitelist, leave it empty..
        /// </summary>
        internal static string Steam_Http403 {
            get {
                return ResourceManager.GetString("Steam_Http403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam rate-limited requests (HTTP 429). Wait a minute and try again..
        /// </summary>
        internal static string Steam_Http429 {
            get {
                return ResourceManager.GetString("Steam_Http429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam responded HTTP {0}..
        /// </summary>
        internal static string Steam_HttpGeneric {
            get {
                return ResourceManager.GetString("Steam_HttpGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Steam Web API Key looks incomplete. Copy it again from steamcommunity.com/dev..
        /// </summary>
        internal static string Steam_IncompleteApiKey {
            get {
                return ResourceManager.GetString("Steam_IncompleteApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SteamID64 does not look valid. It must be a 17-digit number (7656119...)..
        /// </summary>
        internal static string Steam_InvalidSteamId {
            get {
                return ResourceManager.GetString("Steam_InvalidSteamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure Steam Web API Key and SteamID64 in widget Settings..
        /// </summary>
        internal static string Steam_MissingCredentials {
            get {
                return ResourceManager.GetString("Steam_MissingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No game was specified. Check the exact game name on Steam..
        /// </summary>
        internal static string Steam_NoGameSpecified {
            get {
                return ResourceManager.GetString("Steam_NoGameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not read Steam achievements response..
        /// </summary>
        internal static string Steam_ParseAchievementsFailed {
            get {
                return ResourceManager.GetString("Steam_ParseAchievementsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam API sees your profile as {0}. For the Web API it must be Public (not Friends only). Steam &gt; your profile &gt; Edit profile &gt; Privacy &gt; My profile: Public..
        /// </summary>
        internal static string Steam_ProfileHidden {
            get {
                return ResourceManager.GetString("Steam_ProfileHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam profile not found. Check your SteamID64..
        /// </summary>
        internal static string Steam_ProfileNotFound {
            get {
                return ResourceManager.GetString("Steam_ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not query Steam: {0}.
        /// </summary>
        internal static string Steam_QueryFailed {
            get {
                return ResourceManager.GetString("Steam_QueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a extended public (5).
        /// </summary>
        internal static string Steam_Visibility_Extended {
            get {
                return ResourceManager.GetString("Steam_Visibility_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a friends only (2).
        /// </summary>
        internal static string Steam_Visibility_Friends {
            get {
                return ResourceManager.GetString("Steam_Visibility_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a private (1).
        /// </summary>
        internal static string Steam_Visibility_Private {
            get {
                return ResourceManager.GetString("Steam_Visibility_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a public (3).
        /// </summary>
        internal static string Steam_Visibility_Public {
            get {
                return ResourceManager.GetString("Steam_Visibility_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a registered users (4).
        /// </summary>
        internal static string Steam_Visibility_Registered {
            get {
                return ResourceManager.GetString("Steam_Visibility_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a unknown ({0}).
        /// </summary>
        internal static string Steam_Visibility_Unknown {
            get {
                return ResourceManager.GetString("Steam_Visibility_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop and send.
        /// </summary>
        internal static string Voice_StopSend {
            get {
                return ResourceManager.GetString("Voice_StopSend", resourceCulture);
            }
        }
    }
}
